### ISSUE TITLE
Mobile Navigation funktioniert nicht

### ISSUE THREAD

**Issue by FlorianBrinkmann** [RRZE-Webteam/FAU-Theme-veraltet-#312]
Hallo!

Wenn ich auf das Hamburger-Icon für das Menü klicke, dann passiert nichts. Getestet einmal mit Firefox 48.0.2 auf Windows 10 und einmal mit Firefox auf Android.

**Comment by xwolfde** [comment]
Liegt am veralteten Theme. Bei FAU-Einrichtungen ist das behoben.

**Comment by FlorianBrinkmann** [comment]
> Bei FAU-Einrichtungen ist das behoben. 
Also auf der FAU-Startseite funktioniert es nicht …

**Comment by xwolfde** [comment]
Die Webredaktion will noch  kein update :/

**Comment by FlorianBrinkmann** [comment]
🙈 achso okay. 
Das Team, das sich um die Verwaltung von de.wordpress.org kümmert, wollte die Site mit in den Showcase aufnehmen, aber dann ist mir das mit der Navi aufgefallen …

**Comment by xwolfde** [comment]
Das Update wird in Bälde kommen. Leider ist das eher so ne organisatorische Geschichte.  
Bei den Fakultäten und den zentralen Einrichtungssites ist das Update schon drin. vgl:
 rw.fau.de
oder die Doku
  wordpress.rrze.fau.de

**Comment by FlorianBrinkmann** [comment]
Wäre es möglich hier einen Ping zu bekommen, wenn das Update gemacht wurde? :)

**Comment by xwolfde** [comment]
Kann ich gern machen. Wir informieren auch ansonsten immer hier: https://blogs.fau.de/webworking/

**Comment by xwolfde** [comment]
@FlorianBrinkmann Ping. Das Update ist jetzt live. Wird zwar noch an anderen Stellen feingetuned, aber es ist nun bei den Mobile Zugriff gefixt

**Comment by FlorianBrinkmann** [comment]
Perfekt, danke für die Nachricht!

**Comment by xwolfde** [comment]
Wir sind übrigens tatsächlich die größte deutsche Uni, die WP auch für ihre zentrale Startseite einsetzt (und dies nicht verbirgt):  http://statistiken.rrze.fau.de/webauftritte/hochschulen/staatlich.shtml ;)

Demnächst wird es hierzu auch einen längeren Artikel in einer neuen Zeitschrift geben, die  von Vladimir Simovic gerade organisiert wird.

**Comment by FlorianBrinkmann** [comment]
Danke für den Hinweis auf die Statistik-Seite! Den Artikel im Magazin werde ich mir dann mal durchlesen :)
